name: Update Gist

# Required secrets: GIST_TOKEN
# https://github.com/settings/tokens/new

env:
  GIST_SHA: bb0540b208019382d08732cc6dd59007

on:
  push:
    paths:
      - 'cancelot.sh'

jobs:
  update-gist:
    runs-on: ubuntu-latest
    name: Update Gist
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push gist
        run: |
          git clone --depth=1 https://${{ secrets.GIST_TOKEN }}@gist.github.com/${GIST_SHA}.git /tmp/gist
          cp cancelot.sh /tmp/gist
          cd /tmp/gist
          git add cancelot.sh
          git -c user.name="${GITHUB_ACTOR}" -c user.email="${GITHUB_ACTOR}@users.noreply.github.com" commit -m "update gist"
          git push
